services:
  - type: web
    name: league-predictor
    env: python
    plan: free
    runtime: python
    pythonVersion: "3.9.18"
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
